services:
  db-escape:
    image: mysql:8.0
    container_name: bd-escape
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Alemao890.
      MYSQL_DATABASE: escape
    volumes:
      - ./bd-escape/scripts:/docker-entrypoint-initdb.d # Scripts de inicialização do banco
      - ./bd-escape/data:/var/lib/mysql # Persistência dos dados
    networks:
      - app-network

  api-escape:
    build:
      context: ./api-escape
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api-escape/.env
    depends_on:
      - db-escape
    networks:
      - app-network
    restart: always

  site_escape:
    build:
      context: ./site_escape
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - api-escape
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
